import React from 'react'
import Head from 'next/head'

export const Meta = ({title,keywords, description}) => {
  return (
    <div>
        <Head>
          <meta name="viewport" content='width=device-width,initial-scale=1'/>
          <meta name="keywords" content={keywords}/>
          <meta name="description" content={description} />
          <meta charSet='utf-8'/>
        <title>{title}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

Meta.defaultProps = {
  title: "Create Next App",
  keywords: "web development, code, next",
  description: "Generated by create next app"
}